import React from 'react';
import { Box, ContainerText, Divider } from './styles';
import { Text } from '../../../Typography/Text/index';

export const DetalhesHistorico = () => {
  return (
    <Box>
      <ContainerText>
        <Text
          fontSize="14px"
          lineHeight="20px"
          color="var(--primary)"
          weight="700"
        >
          Histórico
        </Text>
        <Text
          fontSize="14px"
          lineHeight="19.6px"
          color="var(--primary)"
          weight="400"
        >
          Histórico
        </Text>
      </ContainerText>
      <ContainerText>
        <Text
          fontSize="14px"
          lineHeight="20px"
          color="var(--primary)"
          weight="700"
        >
          Histórico
        </Text>
        <Text
          fontSize="14px"
          lineHeight="19.6px"
          color="var(--primary)"
          weight="400"
        >
          Histórico
        </Text>
      </ContainerText>
      <Divider />
      <ContainerText>
        <Text
          fontSize="14px"
          lineHeight="20px"
          color="var(--primary)"
          weight="700"
        >
          Histórico
        </Text>
        <Text
          fontSize="14px"
          lineHeight="19.6px"
          color="var(--primary)"
          weight="400"
        >
          Histórico
        </Text>
      </ContainerText>
      <ContainerText>
        <Text
          fontSize="14px"
          lineHeight="20px"
          color="var(--primary)"
          weight="700"
        >
          Histórico
        </Text>
        <Text
          fontSize="14px"
          lineHeight="19.6px"
          color="var(--primary)"
          weight="400"
        >
          Histórico
        </Text>
      </ContainerText>
      <ContainerText>
        <Text
          fontSize="14px"
          lineHeight="20px"
          color="var(--primary)"
          weight="700"
        >
          Histórico
        </Text>
        <Text
          fontSize="14px"
          lineHeight="19.6px"
          color="var(--primary)"
          weight="400"
        >
          Histórico
        </Text>
      </ContainerText>
    </Box>
  );
};
